[package]
name = "auto-configuration"
version = "0.1.0"
authors = ["navyd <dhjnavyd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0"
scheduled-thread-pool = "0.2.5"
regex = "1"
